title: Pil Kwon
author: Pil Kwon
description: Pil's Map Blog based on Jekyll brume theme.

highlighter: null
permalink: /:title

url: https://pil0706.github.io
baseurl:

google_analytics_id: UA-142465068-1

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
