title: Pil's Blog
author: Pil Kwon
description: Pil's Blog based on Jekyll theme.

highlighter: null
permalink: /:title

url: https://pil0706.github.io/
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
